export const data = `
classes -> java.base
classes -> not found
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.io.File                                       java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.io.FileOutputStream                           java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.io.IOException                                java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.io.InputStream                                java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.lang.Object                                   java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.lang.String                                   java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.lang.Throwable                                java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.nio.file.Files                                java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.nio.file.Path                                 java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.nio.file.attribute.FileAttribute              java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.util.zip.ZipEntry                             java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> java.util.zip.ZipInputStream                       java.base
   site.gutschi.dependency.jdeps.FatJarUnzipper       -> site.gutschi.dependency.jdeps.JDepsException       classes
   site.gutschi.dependency.jdeps.JDepsException       -> java.io.File                                       java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.io.IOException                                java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.lang.Exception                                java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.lang.Object                                   java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.lang.RuntimeException                         java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.lang.String                                   java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.lang.Throwable                                java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.lang.invoke.CallSite                          java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.lang.invoke.MethodHandles                     java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.lang.invoke.MethodHandles$Lookup              java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.lang.invoke.MethodType                        java.base
   site.gutschi.dependency.jdeps.JDepsException       -> java.lang.invoke.StringConcatFactory               java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.io.File                                       java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.io.FileInputStream                            java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.io.IOException                                java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.io.InputStream                                java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.io.OutputStream                               java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.io.PrintStream                                java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.io.PrintWriter                                java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.io.StringWriter                               java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.io.Writer                                     java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.Boolean                                  java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.Exception                                java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.Object                                   java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.String                                   java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.System                                   java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.Throwable                                java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.invoke.CallSite                          java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.invoke.LambdaMetafactory                 java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.invoke.MethodHandle                      java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.invoke.MethodHandles                     java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.invoke.MethodHandles$Lookup              java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.lang.invoke.MethodType                        java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.nio.file.Files                                java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.nio.file.Path                                 java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.Arrays                                   java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.LinkedList                               java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.List                                     java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.Objects                                  java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.Optional                                 java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.function.Consumer                        java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.function.Function                        java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.function.IntFunction                     java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.function.Predicate                       java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.spi.ToolProvider                         java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> java.util.stream.Stream                            java.base
   site.gutschi.dependency.jdeps.JDepsRunner          -> site.gutschi.dependency.jdeps.FatJarUnzipper       classes
   site.gutschi.dependency.jdeps.JDepsRunner          -> site.gutschi.dependency.jdeps.JDepsException       classes
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.io.File                                       java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.io.FileInputStream                            java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.io.IOException                                java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.io.InputStream                                java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.io.OutputStream                               java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.io.PrintStream                                java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.io.PrintWriter                                java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.io.StringWriter                               java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.io.Writer                                     java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.Boolean                                  java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.Exception                                java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.Object                                   java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.String                                   java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.System                                   java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.Throwable                                java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.invoke.CallSite                          java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.invoke.LambdaMetafactory                 java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.invoke.MethodHandle                      java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.invoke.MethodHandles                     java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.invoke.MethodHandles$Lookup              java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.lang.invoke.MethodType                        java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.nio.file.Files                                java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.nio.file.Path                                 java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.Arrays                                   java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.LinkedList                               java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.List                                     java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.Objects                                  java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.Optional                                 java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.function.Consumer                        java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.function.Function                        java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.function.IntFunction                     java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.function.Predicate                       java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.spi.ToolProvider                         java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> java.util.stream.Stream                            java.base
   site.gutschi.dependency.jdeps.JavadocRunner        -> site.gutschi.dependency.jdeps.FatJarUnzipper       classes
   site.gutschi.dependency.jdeps.JavadocRunner        -> site.gutschi.dependency.jdeps.JDepsException       classes
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.io.File                                       java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.io.IOException                                java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.lang.CharSequence                             java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.lang.Class                                    java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.lang.Object                                   java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.lang.String                                   java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.lang.Throwable                                java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.lang.invoke.CallSite                          java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.lang.invoke.MethodHandles                     java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.lang.invoke.MethodHandles$Lookup              java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.lang.invoke.MethodType                        java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.lang.invoke.StringConcatFactory               java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.net.URL                                       java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.nio.charset.Charset                           java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.nio.charset.StandardCharsets                  java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.nio.file.Files                                java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.nio.file.OpenOption                           java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.nio.file.Path                                 java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> java.nio.file.Paths                                java.base
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> org.apache.commons.io.IOUtils                      not found
   site.gutschi.dependency.nomnoml.NomnomlWriter      -> site.gutschi.dependency.nomnoml.NomnumlException   classes
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.io.File                                       java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.io.IOException                                java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.lang.Object                                   java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.lang.RuntimeException                         java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.lang.String                                   java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.lang.Throwable                                java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.lang.invoke.CallSite                          java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.lang.invoke.MethodHandles                     java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.lang.invoke.MethodHandles$Lookup              java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.lang.invoke.MethodType                        java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.lang.invoke.StringConcatFactory               java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.net.URL                                       java.base
   site.gutschi.dependency.nomnoml.NomnumlException   -> java.nio.file.Path                                 java.base
`;
